[package]
name = "smpl_jwt"
version = "0.2.0"
authors = ["Drazen Urch <github@drazenur.ch>"]
description = "Very simple JWT generation lib."
repository = "https://github.com/durch/rust-jwt"
readme = "README.md"
keywords = ["JWT"]
license = "MIT"
documentation = "https://durch.github.io/rust-jwt"

[lib]
name = "smpl_jwt"
path = "src/lib.rs"

[dependencies]
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
rustc-serialize = "0.3"
openssl = "^0.9"
time = "0.1.35"
log = "0.3.6"
